### ISSUE TITLE
PhotoGIMP 2020 file size is bigger than PhotoGIMP 2020.1 because has fonts inside ?

### ISSUE THREAD

**Issue by Augusto7743** [Diolinux/PhotoGIMP#73]
Hello.
Thanks for read my topic.
Previous PhotoGIMP 2020 file size is bigger than 30 MB and current version is less than 10 MB.
Previous PhotoGIMP 2020 has fonts inside ? If yes are free ? Is possible use fonts from previous version without problems with PhotoGIMP 2020.1 ?

Have an nice day.

**Comment by momentoalmir** [comment]
Hello @Augusto7743 .
Mostly because the fonts, and [minors updates listed here](https://github.com/Diolinux/PhotoGIMP/releases/tag/1.1).

> Previous PhotoGIMP 2020 has fonts inside ?
Yes.

> If yes are free ?
All of this fonts are supposed to be free to use, but, you may have to [check its individual licences for commercial purposes](https://github.com/Diolinux/PhotoGIMP/blob/master/fonts.txt).

> Is possible use fonts from previous version without problems with PhotoGIMP 2020.1 ?
Yes, don't worry. You can still [download the full project in master branch](https://github.com/Diolinux/PhotoGIMP/archive/refs/heads/master.zip) that should include all fonts included in that list, or you could just include every font you need in `2.10/fonts` folder.
