### ISSUE TITLE
Is the project still alive

### ISSUE THREAD

**Issue by Sabering1** [Diolinux/PhotoGIMP#99]
bottom text

**Comment by Diolinux** [comment]
To be fair, I don't have much time to look into it, but since GIMP have a slow pace on updating at it's own, and these "photogimp project" are simple configuration files, the project is still working perfectly on GIMP, in the flatpak version at least.
For what it is worth, you can create your own "photogimp" by simply changing the settings on a regular GIMP installation, no code required, the end result will very close to this.

**Comment by Sabering1** [comment]
Thanks for the answer man!
